version: '3.8'
services:
  app:
    build: .
    ports:
      - "3001:3001"
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - ALLOWED_ORIGIN=https://audiomax-jo3yc.ondigitalocean.app,https://audiomax.ai
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start
