[build]
  command = "npm run build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/v2/*"
  to = "https://api.play.ht/api/v2/:splat"
  status = 200
  force = true
  headers = {Authorization = "Bearer ${PLAYHT_SECRET_KEY}", X-User-ID = "${PLAYHT_USER_ID}"}

[[redirects]]
  from = "/api/auth/*"
  to = "https://audiomax.onrender.com/api/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://audiomax.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
