[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/v2/*"
  to = "https://api.play.ht/api/v2/:splat"
  status = 200
  force = true
  headers = {
    Authorization = ":Authorization",
    X-User-ID = ":X-User-ID",
    Access-Control-Allow-Origin = "*",
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS",
    Access-Control-Allow-Headers = "Authorization, X-User-ID, Content-Type",
    Access-Control-Max-Age = "86400"
  }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Authorization, X-User-ID, Content-Type"
