name: audiomax
region: nyc
services:
- name: api
  github:
    repo: arcanadraconi/audiomax
    branch: main
    deploy_on_push: true
  build_command: |
    npm install -g typescript
    npm install -g vite
    npm ci
    npm i -D @types/react-dom @types/firebase @types/jest
    npm run build
  run_command: cd server && node index.js
  environment_slug: node-js
  envs:
  - key: NODE_ENV
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: PORT
    scope: RUN_AND_BUILD_TIME
    value: "3001"
  - key: ALLOWED_ORIGIN
    scope: RUN_AND_BUILD_TIME
    value: "https://audiomax-jo3yc.ondigitalocean.app,https://audiomax.ai"
  - key: PLAYHT_SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: PLAYHT_USER_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  http_port: 3001
  instance_count: 1
  instance_size_slug: basic-xxs
  source_dir: /
ingress:
  rules:
  - component:
      name: api
    match:
      path:
        prefix: /
