name: audiomax
region: nyc
services:
- name: api
  github:
    repo: arcanadraconi/audiomax
    branch: main
    deploy_on_push: true
  build_command: |
    rm -rf dist node_modules
    npm install -g typescript
    npm ci
    npm run build
  run_command: cd server && node index.js
  environment_slug: node-js
  envs:
  - key: NODE_ENV
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: PORT
    scope: RUN_AND_BUILD_TIME
    value: "3001"
  - key: ALLOWED_ORIGIN
    scope: RUN_AND_BUILD_TIME
    value: "https://audiomax-jo3yc.ondigitalocean.app,https://audiomax.ai"
  - key: VITE_FIREBASE_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: "AIzaSyCzTW_1xnJSihqWkH_toKP_tH702WpNlkA"
  - key: VITE_FIREBASE_AUTH_DOMAIN
    scope: RUN_AND_BUILD_TIME
    value: "audiomax-40b0e.firebaseapp.com"
  - key: VITE_FIREBASE_PROJECT_ID
    scope: RUN_AND_BUILD_TIME
    value: "audiomax-40b0e"
  - key: VITE_FIREBASE_STORAGE_BUCKET
    scope: RUN_AND_BUILD_TIME
    value: "audiomax-40b0e.firebasestorage.app"
  - key: VITE_FIREBASE_MESSAGING_SENDER_ID
    scope: RUN_AND_BUILD_TIME
    value: "408318389901"
  - key: VITE_FIREBASE_APP_ID
    scope: RUN_AND_BUILD_TIME
    value: "1:408318389901:web:6f0820b135a52d79563cc4"
  - key: VITE_FIREBASE_MEASUREMENT_ID
    scope: RUN_AND_BUILD_TIME
    value: "G-NZSC3F0QWL"
  - key: VITE_PLAYHT_SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    value: "d0a2b1dc4c9b4e8ca938672b65a6088c"
  - key: VITE_PLAYHT_USER_ID
    scope: RUN_AND_BUILD_TIME
    value: "3I0uk4sKefXqOKsu6Yb9DDIfGrg1"
  - key: VITE_OPENROUTER_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: "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"
  - key: VITE_ENABLE_VOICE_CLONING
    scope: RUN_AND_BUILD_TIME
    value: "true"
  - key: VITE_ENABLE_CUSTOM_VOICES
    scope: RUN_AND_BUILD_TIME
    value: "true"
  - key: VITE_ENABLE_ANALYTICS
    scope: RUN_AND_BUILD_TIME
    value: "true"
  - key: VITE_ENABLE_PUSH_NOTIFICATIONS
    scope: RUN_AND_BUILD_TIME
    value: "false"
  - key: VITE_STRIPE_PUBLISHABLE_KEY
    scope: RUN_AND_BUILD_TIME
    value: "pk_test_51QJcWMGTXKQOsgznvEcIRLI3gVc0wuICwLJhnIpWRNxNrarG4ayb9Of4yfUcOl0NGEpvSKgkLGFPHdNmZs7XAb5700UOpPtsAn"
  http_port: 3001
  instance_count: 1
  instance_size_slug: basic-xxs
  source_dir: /
ingress:
  rules:
  - component:
      name: api
    match:
      path:
        prefix: /
