name: audiomax
services:
- name: web
  github:
    repo: arcanadraconi/audiomax
    branch: main
    deploy_on_push: true
  build_command: |
    npm ci
    npm run build
  run_command: npm start
  envs:
  - key: NODE_ENV
    value: production
    scope: RUN_AND_BUILD_TIME
  - key: PORT
    value: "3001"
    scope: RUN_AND_BUILD_TIME
  - key: ALLOWED_ORIGIN
    value: "https://audiomax-jo3yc.ondigitalocean.app,https://audiomax.ai"
    scope: RUN_AND_BUILD_TIME
  - key: VITE_PLAYHT_SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: VITE_PLAYHT_USER_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  http_port: 3001
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  source_dir: /
  environment_slug: node-js
