name: audiomax
region: nyc
services:
- name: api
  github:
    repo: arcanadraconi/audiomax
    branch: main
    deploy_on_push: true
  build_command: |
    npm install -g typescript
    npm ci
    npm run build
  run_command: cd server && node index.js
  environment_slug: node-js
  envs:
  - key: NODE_ENV
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: PORT
    scope: RUN_AND_BUILD_TIME
    value: "3001"
  - key: ALLOWED_ORIGIN
    scope: RUN_AND_BUILD_TIME
    value: "https://audiomax-jo3yc.ondigitalocean.app,https://audiomax.ai"
  - key: VITE_FIREBASE_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: VITE_FIREBASE_AUTH_DOMAIN
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: VITE_FIREBASE_PROJECT_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: VITE_FIREBASE_STORAGE_BUCKET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: VITE_FIREBASE_MESSAGING_SENDER_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: VITE_FIREBASE_APP_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: VITE_FIREBASE_MEASUREMENT_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: VITE_PLAYHT_SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: VITE_PLAYHT_USER_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: VITE_OPENROUTER_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: VITE_ENABLE_VOICE_CLONING
    scope: RUN_AND_BUILD_TIME
    value: "true"
  - key: VITE_ENABLE_CUSTOM_VOICES
    scope: RUN_AND_BUILD_TIME
    value: "true"
  - key: VITE_ENABLE_ANALYTICS
    scope: RUN_AND_BUILD_TIME
    value: "false"
  - key: VITE_ENABLE_PUSH_NOTIFICATIONS
    scope: RUN_AND_BUILD_TIME
    value: "true"
  - key: VITE_STRIPE_PUBLISHABLE_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: VITE_STRIPE_PRICE_ID_PRO_MONTHLY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: VITE_STRIPE_PRICE_ID_PRO_YEARLY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: VITE_STRIPE_PRICE_ID_PREMIUM_MONTHLY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: VITE_STRIPE_PRICE_ID_PREMIUM_YEARLY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: VITE_MONGODB_URI
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  http_port: 3001
  instance_count: 1
  instance_size_slug: basic-xxs
  source_dir: /
ingress:
  rules:
  - component:
      name: api
    match:
      path:
        prefix: /
